export * from "./basics.schema";
export * from "./course.schema";
export * from "./cv.schema";
export * from "./education.schema";
export * from "./location.schema";
export * from "./profile.schema";
export * from "./projects.schema";
export * from "./skills.schema";
export * from "./work.schema";
